### ISSUE TITLE
Edit default value

### ISSUE THREAD

**Issue by v8oss** [manifoldco/promptui#44]
It'd be really handy if there were an option to allow the default value to be edited. At the moment it gets deleted if you try.

Use case is e.g. asking for something like a hostname where you may want to make a minor adjustment rather than accept the default.

**Comment by luizbranco** [comment]
@v8oss can you give a try https://github.com/manifoldco/promptui/pull/45

**Comment by Larchy** [comment]
This line in Prompt.go blanks out default values for confirm prompt types.
https://github.com/manifoldco/promptui/blob/master/prompt.go#L257
```
if p.IsConfirm {
	p.Default = ""                                                    // This line
	if tpls.Confirm == "" {
		confirm := "y/N"
		if strings.ToLower(p.Default) == "y" {    // Causes this logic to fail
			confirm = "Y/n"
		}
```
As well as the logic to accept `Y` as a default . I haven't had time to research where the fix for this would be and it's not a high priority for me right now.
By removing `p.Default = ""`, functionality does work except the Default is displayed on the input, similar to normal prompts, which didn't seem desired since the default functionality with `N` as default doesn't show "N" on the input.
